In [2]:
import fastf1
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
session = fastf1.get_session(2024, 'Bahrain Grand Prix', 'Q')
session.load()

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) C:\Users\sukir\AppData\Local\Temp\fastf1
core           INFO 	Loading data for Bahrain Grand Prix - Qualifying [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '11', '14', '4', '81', '44', '27', '22', '18', '23', '3', '20', '77', '24', '2', '31', '10']

In [6]:
#print(session.event)
#print(session.name)
print(session.results.head())
#print(session.laps.head())

   DriverNumber BroadcastName Abbreviation        DriverId         TeamName  \
1             1  M VERSTAPPEN          VER  max_verstappen  Red Bull Racing
16           16     C LECLERC          LEC         leclerc          Ferrari
63           63     G RUSSELL          RUS         russell         Mercedes
55           55       C SAINZ          SAI           sainz          Ferrari
11           11       S PEREZ          PER           perez  Red Bull Racing

   TeamColor    TeamId FirstName    LastName         FullName  ... Position  \
1     3671c6  red_bull       Max  Verstappen   Max Verstappen  ...      1.0
16    e8002d   ferrari   Charles     Leclerc  Charles Leclerc  ...      2.0
63    27f4d2  mercedes    George     Russell   George Russell  ...      3.0
55    e8002d   ferrari    Carlos       Sainz     Carlos Sainz  ...      4.0
11    3671c6  red_bull    Sergio       Perez     Sergio Perez  ...      5.0

   ClassifiedPosition  GridPosition                     Q1  \
1                               NaN 0 days 00:01:30.031000
16                              NaN 0 days 00:01:30.243000
63                              NaN 0 days 00:01:30.350000
55                              NaN 0 days 00:01:29.909000
11                              NaN 0 days 00:01:30.221000

                       Q2                     Q3 Time Status Points Laps
1  0 days 00:01:29.374000 0 days 00:01:29.179000  NaT           NaN  NaN
16 0 days 00:01:29.165000 0 days 00:01:29.407000  NaT           NaN  NaN
63 0 days 00:01:29.922000 0 days 00:01:29.485000  NaT           NaN  NaN
55 0 days 00:01:29.573000 0 days 00:01:29.507000  NaT           NaN  NaN
11 0 days 00:01:29.932000 0 days 00:01:29.537000  NaT           NaN  NaN

[5 rows x 22 columns]

In [7]:
session.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:22:20.980000,VER,1,NaT,1.0,1.0,0 days 00:20:10.428000,NaT,NaT,0 days 00:00:46.454000,...,True,Red Bull Racing,0 days 00:20:10.428000,2024-03-01 16:06:46.101,1,NaN,False,,False,False
1,0 days 00:23:51.011000,VER,1,0 days 00:01:30.031000,2.0,1.0,NaT,NaT,0 days 00:00:28.787000,0 days 00:00:38.580000,...,True,Red Bull Racing,0 days 00:22:20.980000,2024-03-01 16:08:56.653,1,NaN,False,,False,True
2,0 days 00:25:59.737000,VER,1,0 days 00:02:08.726000,3.0,1.0,NaT,0 days 00:25:58.003000,0 days 00:00:37.524000,0 days 00:00:56.168000,...,True,Red Bull Racing,0 days 00:23:51.011000,2024-03-01 16:10:26.684,1,NaN,False,,False,False
3,0 days 00:31:09.934000,VER,1,NaT,4.0,2.0,0 days 00:29:18.091000,NaT,NaT,0 days 00:00:46.144000,...,False,Red Bull Racing,0 days 00:25:59.737000,2024-03-01 16:12:35.410,1,NaN,False,,False,False
4,0 days 00:32:40.094000,VER,1,0 days 00:01:30.160000,5.0,2.0,NaT,NaT,0 days 00:00:28.822000,0 days 00:00:38.767000,...,False,Red Bull Racing,0 days 00:31:09.934000,2024-03-01 16:17:45.607,1,NaN,False,,False,True

In [8]:
session.laps.describe()

,Time,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,LapStartTime,LapStartDate,Position
count,267,169,267.000000,267.000000,92,92,175,267,261,175,267,261,267.000000,267.000000,175.000000,267.000000,267.000000,267,267,0.0
mean,0 days 00:42:59.339554307,0 days 00:01:42.647011834,7.868914,3.071161,0 days 00:39:14.367380434,0 days 00:44:31.341793478,0 days 00:00:32.708754285,0 days 00:00:44.971367041,0 days 00:00:26.715590038,0 days 00:42:42.703502857,0 days 00:42:32.540329588,0 days 00:42:14.555448275,213.857678,232.022472,286.188571,206.891386,2.704120,0 days 00:39:53.096393258,2024-03-01 16:26:28.769393408,NaN
min,0 days 00:15:27.765000,0 days 00:01:29.165000,1.000000,1.000000,0 days 00:13:35.553000,0 days 00:18:54.679000,0 days 00:00:28.509000,0 days 00:00:38.059000,0 days 00:00:22.263000,0 days 00:15:57.525000,0 days 00:15:02.698000,0 days 00:15:28.005000,85.000000,114.000000,261.000000,31.000000,1.000000,0 days 00:13:35.553000,2024-03-01 16:00:11.226000,NaN
25%,0 days 00:26:18.048500,0 days 00:01:30.425000,4.000000,2.000000,0 days 00:21:37.954750,0 days 00:27:01.617000,0 days 00:00:29.016500,0 days 00:00:38.983000,0 days 00:00:22.714000,0 days 00:25:12.254500,0 days 00:25:44.624500,0 days 00:26:05.427000,199.000000,210.500000,285.000000,109.000000,1.000000,0 days 00:24:10.854500,2024-03-01 16:10:46.527500032,NaN
50%,0 days 00:43:27.187000,0 days 00:01:32.434000,7.000000,3.000000,0 days 00:40:16.884000,0 days 00:45:40.274500,0 days 00:00:30.903000,0 days 00:00:45.848000,0 days 00:00:26.279000,0 days 00:43:32.137000,0 days 00:43:00.787000,0 days 00:43:03.147000,219.000000,233.000000,286.000000,230.000000,2.000000,0 days 00:33:34.773000,2024-03-01 16:20:10.446000128,NaN
75%,0 days 00:54:43.638500,0 days 00:01:54.230000,11.000000,4.000000,0 days 00:50:15.018000,0 days 00:55:10.597500,0 days 00:00:35.913500,0 days 00:00:48.333500,0 days 00:00:29.260000,0 days 00:53:36.628500,0 days 00:54:09.841000,0 days 00:54:09.779000,241.000000,270.000000,288.000000,313.000000,3.000000,0 days 00:52:48.171000,2024-03-01 16:39:23.844000,NaN
max,0 days 01:16:31.161000,0 days 00:02:09.967000,19.000000,7.000000,0 days 01:11:12.697000,0 days 01:16:31.161000,0 days 00:00:46.998000,0 days 00:01:02.636000,0 days 00:00:39.337000,0 days 01:15:12.107000,0 days 01:15:58.692000,0 days 01:16:19.607000,244.000000,274.000000,293.000000,327.000000,8.000000,0 days 01:14:33.657000,2024-03-01 17:01:09.330000,NaN
std,0 days 00:17:43.011981974,0 days 00:00:13.404649176,4.779504,1.676516,0 days 00:17:38.102117791,0 days 00:17:35.120515024,0 days 00:00:04.272272739,0 days 00:00:05.049205164,0 days 00:00:03.914754524,0 days 00:17:47.203952872,0 days 00:17:42.858335444,0 days 00:17:12.557292380,28.964627,35.183187,2.767605,101.267565,1.523778,0 days 00:17:30.419941613,NaN,NaN